name: 'Deploy to Kubernetes cluster'
description: 'Deploy to Kubernetes cluster via kubebot'
inputs:
  environment:
    description: '[dev|prod]'
    required: true
  namespace:
    description: 'Choose the target Kubernetes namespace.'
    required: false
  service:
    description: 'Name of the service in the cluster.'
    required: false
  tag:
    description: 'Docker image tag'
    required: false
  registry:
    description: 'The container registry where the docker image is'
    required: false
  repository:
    description: 'The repository in the container registry'
    required: false
    default: 'webjet'
  manifest:
    description: 'Path to the manifest file which will be used for deployment'
    required: true
  deploytoprod:
    description: 'Flag Deploy to Prod.'
    required: false    
  xwatch:
    description: 'Flag to check deployment.'
    required: false   
    default: 'true'  
runs:
  using: 'node12'
  main: 'dist/index.js'